version: 2.1

executors:
  my-executor:
    docker:
      - image: circleci/node:11
    working_directory: ~/mobx

jobs:
  more-nothing:
    executor: my-executor
    steps:
      - run: echo "hello"

workflows:
  version: 2
  do-nothing:
    jobs:
      - more-nothing: {}
