version: 2.1

executors:
  my-executor:
    docker:
      - image: circleci/node:11
        environment:
          CI: true
    working_directory: ~/mobx

jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - run: ./build.sh
